backend ="glx";

active-opacity = 10;
frame-opacity = 0.6;

blur-kern = "3x3box";
blur-method = "kawase";
blur-strength = 3;
opacity-rule = [
  "90:class_g = 'Alacritty'",
  "90:class_g = 'Nemo'",
  "90:class_g = 'Pluma'",
  "90:class_g = 'Firefox'"
]

####################### SHADOW #########################################
shadow = true;

# The blur radius for shadows, in pixels. (defaults to 12)
shadow-radius = 14;

# The opacity of shadows. (0.0 - 1.0, defaults to 0.75)
shadow-opacity = 0.30;

