#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom -fb --config ~/.config/picom/picom.conf &
nitrogen --restore &
sh ~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap		 5

bspc config split_ratio          0.54
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config focus_follows_pointer	true

bspc config normal_border_color           "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

